name: Build and deploy frontend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm 
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Running lints
        run: pnpm lint

      - name: Running prettier
        run: pnpm format

      - name: Running tests
        run: pnpm test:unit

      - name: Building project
        run: pnpm build